
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JTabbedPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Home.java
 *
 * Created on Feb 23, 2016, 11:17:06 AM
 */

public class Home extends javax.swing.JFrame {

    /** Creates new form Home */
    int userId = 0;


    public Home(int uId) {
        initComponents();

        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        userId = uId;

        JFrame frame = new JFrame("Home");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        JTabbedPane tPane = new JTabbedPane();
        
        tPane.add("Inventory", new InventoryMainFrame(userId).getContentPane());
        frame.setSize(1200 , 1200);
        
        tPane.add("Orders", new OrderFrame(userId).getContentPane());
        frame.setSize(1200, 1200);

        tPane.add("Shipping", new ShippingFrame(userId).getContentPane());
        frame.setSize(1200, 1200);

        frame.add(tPane);       
        frame.setVisible(true);

        Boolean connectError = false;   // Error flag
        Connection DBConn = null;       // MySQL connection handle
        Boolean executeError = false;   // Error flag
        String errString = null;        // String for displaying errors
        Boolean fieldError = false;     // Error flag
        String msgString = null;        // String for displaying non-error messages
        ResultSet res = null;           // SQL query result set pointer
        java.sql.Statement s = null;    // SQL statement pointer
        String SQLstatement = null;     // String for building SQL queries


        try {
            msgString = ">> Establishing Driver...";
            Class.forName("com.mysql.jdbc.Driver");
            msgString = ">> Setting up URL...";
            String sourceURL = "jdbc:mysql://localhost:3306/leaftech";
            msgString = ">> Establishing connection with: " + sourceURL + "...";

            DBConn = DriverManager.getConnection(sourceURL, "remote", "remote_pass");

        } catch (Exception e) {

            errString = "\nProblem connecting to database:: " + e;
            connectError = true;

        }
        if (!connectError && !fieldError) {
            try {
                s = DBConn.createStatement();

                res = s.executeQuery("Select inventoryflag, orderflag, shippingflag from users.users where userId=" + userId);
                if (res.next()) {
                    if (res.getString(1).equalsIgnoreCase("false")) {
                        tPane.setEnabledAt(0, false);
                        tPane.setSelectedIndex(1);
                    }
                    if (res.getString(2).equalsIgnoreCase("false")) {
                        tPane.setEnabledAt(1, false);
                        if (res.getString(1).equalsIgnoreCase("false")) {
                            tPane.setSelectedIndex(2);
                        }
                    }
                    if (res.getString(3).equalsIgnoreCase("false")) {
                        tPane.setEnabledAt(2, false);
                    }

                }               
                
            } catch (Exception e) {

                errString = "\nError :: " + e;
                executeError = true;

            }
        }

        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       new Home(1).setVisible(false);


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
